### ISSUE TITLE
TypeError: res.status is not a function

### ISSUE THREAD

**Issue by SyedMSawaid** [SaadShah11/love-calculator-backend#2]
```
Adam
Sara
undefined
{
  fname: 'Adam',
  sname: 'Sara',
  percentage: '46',
  result: 'Can choose someone better.'
}
D:\love-calculator-backend\controllers\loveCalculator.js:41
        res.status(200).send(JSON.stringify(res.body));
            ^

TypeError: res.status is not a function
    at D:\love-calculator-backend\controllers\loveCalculator.js:41:13
    at Request.handleRequestResponse [as _callback] (D:\love-calculator-backend\node_modules\unirest\index.js:552:70)
    at Request.self.callback (D:\love-calculator-backend\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (D:\love-calculator-backend\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (D:\love-calculator-backend\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
PS D:\love-calculator-backend>
```

It is still now working. This is the result I get in the terminal. And please don't close the issue this fast.

**Comment by SaadShah11** [comment]
![Screenshot (51)](https://user-images.githubusercontent.com/34264037/114548396-23c4ad80-9c79-11eb-8333-f4f255b4f6db.png)
Fixed!
